-- Create the table anew
create table bookmarks_store (
    id INTEGER primary key generated by default as identity,
    title TEXT NOT NULL,
    url_path TEXT NOT NULL,
    rating INTEGER NOT NULL,
    descr TEXT
);